version: '3'
services:
  datajoint:
    build: .
    environment:
      - DJ_HOST=db_gao2018
      - DJ_USER=root
      - DJ_PASS=simple
    volumes:
      - ./notebooks:/notebooks
      - ./images:/images
      - .:/src/gao2018
      - ./data:/data
    links:
      - db_gao2018
    ports:
      - "8890:8888"
  db_gao2018:
    image: datajoint/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=simple
    ports:
      - "4306:3306"
