version: '3'
services:
  datajoint:
    build: .
    env_file: .env
    volumes:
      - ./notebooks:/notebooks
      - ./images:/images
      - .:/src/gao2018
      - ./data:/data
    ports:
      - "8892:8888"

